#cloud-config

package_update: true

packages:
  - mariadb-server
  - python3-pymysql
  - wget

runcmd:
  - wget -O /tmp/99-openstack.cnf https://raw.githubusercontent.com/GSingul/infrastructure/refs/heads/master/infomaniak/database/99-openstack.cnf
  - cp /tmp/99-openstack.cnf /etc/mysql/mariadb.conf.d/99-openstack.cnf
  - wget -O /tmp/db.sql https://raw.githubusercontent.com/GSingul/infrastructure/refs/heads/master/infomaniak/database/db.sql
  - mysql < /tmp/db.sql
  - systemctl restart mariadb
  - systemctl enable mariadb

final_message: "The system is finally up, after $UPTIME seconds"